#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-fTrading
Version  : 3042.79
Release  : 12
URL      : https://cran.r-project.org/src/contrib/fTrading_3042.79.tar.gz
Source0  : https://cran.r-project.org/src/contrib/fTrading_3042.79.tar.gz
Summary  : Rmetrics - Trading and Rebalancing Financial Instruments
Group    : Development/Tools
License  : GPL-2.0+
BuildRequires : R-fBasics
BuildRequires : R-timeDate
BuildRequires : R-timeSeries
BuildRequires : buildreq-R

%description
instruments. It implements various technical indicators to analyse time series such
	as moving averages or stochastic oscillators.

%prep
%setup -q -c -n fTrading

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552898307

%install
export SOURCE_DATE_EPOCH=1552898307
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library fTrading
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library fTrading
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library fTrading
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc  fTrading || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/fTrading/COPYRIGHT.html
/usr/lib64/R/library/fTrading/DESCRIPTION
/usr/lib64/R/library/fTrading/INDEX
/usr/lib64/R/library/fTrading/Meta/Rd.rds
/usr/lib64/R/library/fTrading/Meta/features.rds
/usr/lib64/R/library/fTrading/Meta/hsearch.rds
/usr/lib64/R/library/fTrading/Meta/links.rds
/usr/lib64/R/library/fTrading/Meta/nsInfo.rds
/usr/lib64/R/library/fTrading/Meta/package.rds
/usr/lib64/R/library/fTrading/NAMESPACE
/usr/lib64/R/library/fTrading/R/fTrading
/usr/lib64/R/library/fTrading/R/fTrading.rdb
/usr/lib64/R/library/fTrading/R/fTrading.rdx
/usr/lib64/R/library/fTrading/help/AnIndex
/usr/lib64/R/library/fTrading/help/aliases.rds
/usr/lib64/R/library/fTrading/help/fTrading.rdb
/usr/lib64/R/library/fTrading/help/fTrading.rdx
/usr/lib64/R/library/fTrading/help/paths.rds
/usr/lib64/R/library/fTrading/html/00Index.html
/usr/lib64/R/library/fTrading/html/R.css
/usr/lib64/R/library/fTrading/tests/doRUnit.R
/usr/lib64/R/library/fTrading/unitTests/Makefile
/usr/lib64/R/library/fTrading/unitTests/runTests.R
/usr/lib64/R/library/fTrading/unitTests/runit.BenchmarkAnalysis.R
/usr/lib64/R/library/fTrading/unitTests/runit.RollingAnalysis.R
/usr/lib64/R/library/fTrading/unitTests/runit.TechnicalAnalysis.R
